### ISSUE TITLE
why do you declare Agent vars globally?

### ISSUE THREAD

**Issue by QasimWani** [hortovanyi/DRLND-Continuous-Control#1]
https://github.com/hortovanyi/DRLND-Continuous-Control/blob/2664225e3cc228f7d81ac5a754348070c6753035/ddpg_agent.py#L55-L60

Could you clarify why you declared `actor_local, actor_target, actor_optimizer` etc. globally, instead of `__init__`?
Is it because of parallel agents (because it gets called once, and other agents haven't been initialized, i doubt this is the case)? 
Because I had declared mine in the `__init__` and the model kept fluctuating, almost as if it found a saddle point.
Would appreciate some explanation.
Thanks.

**Comment by hortovanyi** [comment]
It’s shared across all instances of the classes ... wrote this 2 years ago now
